#include "course.h"
#include "professor.h"




void course::getDetails()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009F8 begin

  
{
}
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void course::showDetails()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009FA begin
{
}
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009FA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void course::change_credit_value()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009FC begin
{
}
// section -84-16-12--58-5a7bba49:16681a0ad49:-8000:00000000000009FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
